"""initial

Revision ID: 6bce74bd9300
Revises: 5b31a9b0a605
Create Date: 2022-07-19 12:08:01.850362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bce74bd9300'
down_revision = '5b31a9b0a605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
